# -*- coding: utf-8 -*-
"""vllm-inference-profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlICRDQdW_WUFBw7m0RIunuWcYDlTXtz
"""

# CELL 1: Imports
from vllm import LLM, SamplingParams

# CELL 2: Load model WITH profiling enabled from the start
import os
os.makedirs("/tmp/vllm_traces", exist_ok=True)  # Create folder to save trace files

llm = LLM(
    model="TheBloke/Mistral-7B-Instruct-v0.2-AWQ",
    quantization="awq",
    dtype="float16",
    profiler_config={                          # ← ADD THIS
        "profiler": "torch",
        "torch_profiler_dir": "/tmp/vllm_traces"
    }
)

# CELL 3: Run inference and measure stats
import time

prompts = ["Explain transformer attention mechanism in detail"] * 8
sampling_params = SamplingParams(temperature=0.7, max_tokens=200)

# --- BEFORE: Measure baseline (no profiling overhead) ---
print("🔥 Running inference...")
start_time = time.time()

llm.start_profile()
outputs = llm.generate(prompts, sampling_params)
llm.stop_profile()

end_time = time.time()
total_time = end_time - start_time

# --- Calculate Stats ---
total_tokens = sum(len(o.outputs[0].token_ids) for o in outputs)
throughput = total_tokens / total_time
avg_tokens_per_request = total_tokens / len(prompts)
ttft_approx = total_time / len(prompts)  # rough estimate

print("\n" + "="*50)
print("📊 PROFILING RESULTS")
print("="*50)
print(f"✅ Total requests:        {len(prompts)}")
print(f"✅ Total tokens generated: {total_tokens}")
print(f"✅ Total time:            {total_time:.2f} seconds")
print(f"✅ Throughput:            {throughput:.1f} tokens/sec")
print(f"✅ Avg tokens/request:    {avg_tokens_per_request:.0f}")
print(f"✅ Approx latency/req:    {ttft_approx:.2f} seconds")
print(f"\n📁 Trace saved to: /tmp/vllm_traces/")
print("   → Download and drag into https://ui.perfetto.dev to visualize!")

# CELL 4 (REPLACEMENT): Test different batch sizes - real optimization on T4
import time

def benchmark_run(llm_instance, num_prompts, label):
    prompts = ["Explain transformer attention mechanism in detail"] * num_prompts
    sampling_params = SamplingParams(temperature=0.7, max_tokens=200)

    start = time.time()
    outputs = llm_instance.generate(prompts, sampling_params)
    elapsed = time.time() - start

    total_tokens = sum(len(o.outputs[0].token_ids) for o in outputs)
    throughput = total_tokens / elapsed
    latency = elapsed / num_prompts

    print(f"\n{'='*45}")
    print(f"🔧 Config: {label}")
    print(f"   Requests:    {num_prompts}")
    print(f"   Throughput:  {throughput:.1f} tokens/sec")
    print(f"   Latency/req: {latency:.2f} sec")
    print(f"   Total time:  {elapsed:.2f} sec")
    return throughput, latency

# Test 1: Already done — 8 requests (your baseline)
print("✅ BASELINE already recorded:")
print("   8 requests | 20.2 tok/s | 9.91 sec/req")

# Test 2: Single request — shows per-request latency without batching
t2, l2 = benchmark_run(llm, 1, "Single Request (no batching)")

# Test 3: 4 requests — medium batch
t3, l3 = benchmark_run(llm, 4, "4 Requests (medium batch)")

# Final comparison table
print("\n" + "="*55)
print("📊 FINAL COMPARISON TABLE")
print("="*55)
print(f"{'Config':<25} {'Throughput':>12} {'Latency/req':>12}")
print("-"*55)
print(f"{'1 request':<25} {t2:>10.1f}   {l2:>10.2f}s")
print(f"{'4 requests':<25} {t3:>10.1f}   {l3:>10.2f}s")
print(f"{'8 requests':<25} {'20.2':>10}   {'9.91':>10}s")
print(f"\n💡 Insight: Batching improves throughput by {20.2/t2:.1f}x vs single request!")

